### ISSUE TITLE
Register button on Login Page gives error

### ISSUE THREAD

**Issue by siddhantkhandelwal** [sharifa2708/Checkmate2019#34]
![screenshot from 2019-02-15 11-49-42](https://user-images.githubusercontent.com/30776850/52838177-c0ca4100-3117-11e9-8744-bc299b90a988.png)

**Comment by siddhantkhandelwal** [comment]
This occurs if a person is logged in as admin.
Redirect superusers directly to the admin page.
Create a dummy team and members for debugging these issues during live game session

**Comment by ashryaagr** [comment]
This issue can be easily solved by creating a team with the admin selected in the field "user" . This can easily be done either through admin interface or can also be done through fixtures/populate.json  . I have implemented the second method i.e. through populate.json in the PR #40 . But when we conduct the event, we might have to do this again though admin interface or through another fixtures file as we won't be using the fixtures file that we are currently using for creating dummy questions and superuser.
