### ISSUE TITLE
Change the text colors on question pop-up

### ISSUE THREAD

**Issue by siddhantkhandelwal** [sharifa2708/Checkmate2019#35]
![screenshot from 2019-02-15 11-52-52](https://user-images.githubusercontent.com/30776850/52838319-3df5b600-3118-11e9-8860-e6c0a02187df.png)

**Comment by siddhantkhandelwal** [comment]
Also, the Instructions and other menu items are overlain on the question menu.

**Comment by rohitrajhans** [comment]
Merge as #31
