### ISSUE TITLE
Score updates not instant

### ISSUE THREAD

**Issue by dush-t** [sharifa2708/Checkmate2019#36]
This is because the score is passed to the template as a context variable, so new score will not be passed till the template is rendered again. And the template is rendered again only if you refresh the page.

A potential fix I can think of is to return a JsonResponse with the new score to the frontend, which can be handeled by ajax.

**Comment by siddhantkhandelwal** [comment]
You can pass the score every time a question is popped up or the client requests for answer validation.

**Comment by dush-t** [comment]
We can't do that. If I pass the score a to /game, it will update after /game is reloaded. But if its reloaded, mario will return to his initial position, which is undesireable. 

In any case, passing a context variable to /game won't work, since no matter when we pass it, for updation it has to be reloaded - which resets the position.

**Comment by siddhantkhandelwal** [comment]
Let the acore be updated only at the points where a question is updated. i.e. Pass the score alng with the question and after submission of answer. This should work fine because I think you are keeping the position of mario on every question/answer request

**Comment by siddhantkhandelwal** [comment]
If this is too daunting to do, go ahead and implement AJAX

**Comment by dush-t** [comment]
We are not keeping the position of mario saved in back-end. We can do that, using a simple post request. But it looks bad if the page is reloaded everytime a person enters an answer. I suggest we keep passing variables into the template as a last resort.

**Comment by rohitrajhans** [comment]
When you handle question validation, send the score back to frontend using ajax requests.
