### ISSUE TITLE
Question text not visible properly

### ISSUE THREAD

**Issue by Saujas** [sharifa2708/Checkmate2019#38]
Question text not being rendered properly. Something to do with z-index in css

**Comment by Saujas** [comment]
![screenshot from 2019-02-15 19-23-19](https://user-images.githubusercontent.com/31803919/52861189-b7f95f80-3157-11e9-80d1-925021e02cf5.png)

**Comment by dush-t** [comment]
Can you share a screenshot? It looks good enough on my browser

**Comment by Saujas** [comment]
@dush-t I had
