### ISSUE TITLE
In the register page, previously entered options should not be visible and also it is not completely responsive

### ISSUE THREAD

**Issue by niravasher** [sharifa2708/Checkmate2019#56]
You can solve this problem by refering to https://stackoverflow.com/questions/1477520/how-to-hide-a-text-inputs-browser-generated-dropdown-list-of-previous-items
![screenshot 33](https://user-images.githubusercontent.com/32176296/53145445-3fb2f400-35c6-11e9-9b87-12436fbc19fd.png)

Also check the bottom most part of the page, it appears completely white

**Comment by rohitrajhans** [comment]
fixed by #58
